"""Answering a comment on a journal card: what the model is told, and what
happens to the answer.

Two properties carry most of the weight here, and neither is about the
text of a reply -- that is the model's job and no test can pin it.

**What it is given, and what it is not.** The prompt has to contain the
entry it is answering about and the comment it is answering, because
without either the reply is invented. And the call has to go out
`restricted` and `stateless`: no tools, no session carried between
comments. A reply generated by something that could run a shell is a very
different feature from the one Edvard asked for.

**The worker never dies and never lies about being busy.** `replyPending`
is what puts "Nova is replying…" on his screen, and the client polls until
it goes false. So it has to go false on *every* path out -- a bridge
error, a vanished comment, an exception nobody predicted -- or that line
stays on the card forever and the poll never stops.
"""

import queue
import time
from unittest.mock import patch

import pytest

from agora_runner import nova_replies


@pytest.fixture(autouse=True)
def _fresh_queue():
    """The queue and the pending set are module state, so a test that left
    something in either would silently change the next one."""
    nova_replies._queue = queue.Queue()
    nova_replies._pending = {}
    nova_replies._failed = {}
    yield

ENTRY_MD = """## Entries

### 2026-08-10 13:32 (Oslo) — Cycle 80

Your idea board lost 1238 characters this morning and I put them back.

The cause was Obsidian's chunked sync, not the capture box.

---
PR: #71 | Outcome: merged
"""

THREAD_MD = """---
type: log
---

# Comments

## New

### Cycle 80 · 2026-08-10 13:54

instant replies would be cool

### Cycle 80 · 2026-08-10 13:47

did we lose any ideas?

#### Nova · 2026-08-10 13:50

No -- it came back verbatim.
"""


_SAME = object()


def _sources(journal=ENTRY_MD, comments=THREAD_MD, single=_SAME, unreadable=()):
    """The two vault reads behind a reply, stubbed.

    `journal_entry_markdown` is the path production actually takes, so it
    carries the entry by default and the folder read is the fallback.
    Passing `single=None` is how a test forces the fallback: that is what
    any disagreement between a filename and its document looks like -- a
    tombstone, a heading that parses to a different cycle, a file added by
    hand without the `NNN-cycle-M` shape.

    `unreadable` is what the folder read could not see, which the fallback
    has to weigh against whether it found the entry anyway. It defaults to
    empty because that is the ordinary case, and it is a parameter rather
    than a fixed `()` because leaving it fixed is what kept the raise on
    that path untestable -- the reviewer on #147 found the old helper had
    stubbed the whole question away.
    """
    return (
        patch.object(
            nova_replies, "journal_entry_markdown",
            return_value=journal if single is _SAME else single,
        ),
        patch.object(
            nova_replies, "journal_folder_best_effort",
            return_value=(journal, list(unreadable)),
        ),
        patch.object(nova_replies, "comments_markdown", return_value=comments),
    )


def _prompt_for(stamp="2026-08-10 13:54"):
    entry, journal, comments = _sources()
    with entry, journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "sure"})) as post, \
            patch.object(nova_replies, "add_reply", return_value=(True, "replied")):
        nova_replies.reply_to(80, stamp)
    return post.call_args[0]


# --- what the model is told ------------------------------------------------


def test_the_prompt_carries_the_entry_it_is_answering_about():
    """Without the entry the reply is invented -- this session has no memory
    of the cycle and no tool to go and look."""
    body = _prompt_for()[2]
    assert "Your idea board lost 1238 characters this morning" in body["prompt"]
    assert "PR: #71" in body["prompt"]


def test_the_prompt_carries_the_comment_being_answered():
    body = _prompt_for()[2]
    assert "instant replies would be cool" in body["prompt"]


def test_the_prompt_carries_the_rest_of_the_thread_including_earlier_replies():
    """It is a conversation on one card, so the earlier turns are context.
    They come from the file rather than from a CLI session -- the call is
    stateless, so this prompt is the only memory it has."""
    body = _prompt_for()[2]
    assert "did we lose any ideas?" in body["prompt"]
    assert "No -- it came back verbatim." in body["prompt"]


def test_a_cycle_s_own_note_in_the_thread_reaches_the_prompt_too():
    """A comment can carry more than one `#### Nova` block: the first is this
    worker's answer, and an hourly cycle appends its own when it acts on the
    comment. Both are part of the conversation the model is continuing.

    This came through by accident until now -- `comment["reply"]` was every
    block glued into one string. It is the worker's own answer alone once the
    blocks are parsed separately, so without this the cycle notes go silently
    missing and the model contradicts what a cycle already told him."""
    thread = THREAD_MD.replace(
        "No -- it came back verbatim.",
        "No -- it came back verbatim.\n\n#### Nova · 2026-08-10 14:05\n\nCycle 81: restored from the backup and boarded as #64.",
    )
    entry, journal, comments = _sources(comments=thread)
    with entry, journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "sure"})) as post, \
            patch.object(nova_replies, "add_reply", return_value=(True, "replied")):
        nova_replies.reply_to(80, "2026-08-10 13:54")
    prompt = post.call_args[0][2]["prompt"]
    assert "Cycle 81: restored from the backup and boarded as #64." in prompt
    # And it is attributed, so the model does not read a cycle's work as its
    # own and answer for something it never did.
    assert "A Nova cycle (2026-08-10 14:05):" in prompt
    assert "You (2026-08-10 13:50):" in prompt


def test_the_earlier_thread_is_ordered_oldest_first_as_the_prompt_claims():
    """The prompt says "oldest first" in so many words, so the model reads
    the exchange in that order. `comments_by_cycle` now hands the thread
    over oldest-first; it used to be newest-first and this was a `reversed`.
    Two earlier comments are the minimum that can tell the two apart."""
    thread = THREAD_MD.replace(
        "### Cycle 80 · 2026-08-10 13:47",
        "### Cycle 80 · 2026-08-10 13:50\n\nand another thing\n\n### Cycle 80 · 2026-08-10 13:47",
    )
    entry, journal, comments = _sources(comments=thread)
    with entry, journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "sure"})) as post, \
            patch.object(nova_replies, "add_reply", return_value=(True, "replied")):
        nova_replies.reply_to(80, "2026-08-10 13:54")
    prompt = post.call_args[0][2]["prompt"]
    assert prompt.index("did we lose any ideas?") < prompt.index("and another thing")


def test_the_comment_being_answered_is_not_repeated_as_earlier_context():
    body = _prompt_for()[2]
    assert body["prompt"].count("instant replies would be cool") == 1


def test_the_system_prompt_says_it_is_not_the_session_that_did_the_work():
    """The one thing it must not do is imply a memory it does not have."""
    body = _prompt_for()[2]
    assert "NOT the session" in body["system"]


def test_the_system_prompt_names_the_pod_the_turn_actually_runs_in():
    """Measured 2026-08-11: asked which pod it ran in, the reply turn said
    `agora-persona-runner`, and reasoned its way there from "a reply turn is
    the same session as the build cycle" -- which the prompt already tells it
    is false. It runs in `nova-site` (that deployment's command is
    `run_nova_site.py`). Nothing in the prompt said so, so the model filled
    the gap and stated the guess as fact.
    """
    system = _prompt_for()[2]["system"]
    assert "`nova-site` pod" in system
    assert "not the `agora-persona-runner` pod" in system


def test_the_prompt_tells_it_not_to_re_explain_its_limits():
    """His capture, 2026-08-14: *"Keep replies to my comments short and
    precise -- don't re-explain what you can/can't do each time, my memory is
    consistent, I don't forget."*

    Three separate paragraphs of this prompt used to push the other way -- do
    not imply you remember, here is what you cannot do, say you did not check
    -- and the replies he was reading opened with all three before answering
    him. The constraints stay; what this pins is that the prompt also says not
    to narrate them. The verbatim ask is in the prompt on purpose: a paraphrase
    of a correction is the thing that drifts back.
    """
    system = _prompt_for()[2]["system"]
    assert "don't re-explain what you can/can't do each time" in system
    assert "do not open with your limitations" in system


def test_the_prompt_asks_for_one_or_two_sentences_not_three():
    """The length guidance and the don't-explain-yourself rule are one ask and
    fail together: leaving the old "two or three sentences" in place gives the
    model room to spend the first of them on a disclaimer.
    """
    system = _prompt_for()[2]["system"]
    assert "One or two sentences" in system
    assert "Two or three sentences" not in system


def test_the_prompt_forbids_announcing_the_missing_memory():
    """The narrowest of the three, and the one that reads as a contradiction
    of the paragraph above it if you only skim: "never imply you remember" is
    about not fabricating, and a model resolving it alone disclaims instead.
    Both halves have to be in the same sentence or the disclaimer comes back.
    """
    system = _prompt_for()[2]["system"]
    assert "never announce that you do not" in system


def test_the_prompts_denial_of_pod_and_repo_tools_matches_the_grant():
    """Both sides of one claim, because either alone passes on its own.

    The prompt tells him there are no pod or repository tools *because this
    pod holds no credentials*. That is only honest while the capabilities are
    genuinely ungranted, so this reads the real system prompt and the real
    grant and requires them to agree -- grant either capability without
    moving the turn to a pod that has them, or drop the sentence while they
    are still absent, and this fails.
    """
    system = _prompt_for()[2]["system"]
    denied_in_prompt = "no pod or repository tools" in system
    granted = {"kubectlRead", "githubRead"} & set(nova_replies.REPLY_CAPS)
    assert denied_in_prompt, "the prompt no longer explains why those tools are missing"
    assert not granted, f"prompt denies pod/repo tools the turn is actually granted: {granted}"


# --- how the call goes out -------------------------------------------------


def test_the_call_is_restricted_and_stateless():
    """`restricted` is the safety property: no shell, no vault, no GitHub,
    so the worst an HTTP POST can provoke is a paragraph. `stateless` keeps
    two comments from sharing a CLI session behind the file's back."""
    body = _prompt_for()[2]
    assert body["restricted"] is True
    assert body["stateless"] is True


def test_the_call_asks_to_run_alongside_a_cycle():
    """Without this the reply queues behind the bridge's invocation lock,
    which a Nova cycle holds for up to 45 minutes -- Edvard asked for an
    answer within ten seconds and got one forty minutes later. The bridge
    still decides: it falls back to the lock near an OAuth refresh, so
    asking is always safe and never asking is the bug."""
    body = _prompt_for()[2]
    assert body["allow_concurrent"] is True


def test_it_goes_to_the_bridge_and_so_can_only_spend_the_subscription():
    """identity.md rule 9. There is no provider to pick here and that is
    deliberate -- the bridge is the subscription, so this path cannot reach
    the metered API even by misconfiguration."""
    method, url = _prompt_for()[:2]
    assert method == "POST"
    assert url.endswith("/generate")
    assert url.startswith(nova_replies.CLAUDE_BRIDGE_URL)


def test_the_model_is_the_configured_one():
    assert _prompt_for()[2]["model"] == nova_replies.NOVA_REPLY_MODEL


# --- what happens to the answer --------------------------------------------


def test_the_answer_is_stored_against_the_comment_it_answers():
    entry, journal, comments = _sources()
    with entry, journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "  Yes. Here it is.  "})), \
            patch.object(nova_replies, "add_reply", return_value=(True, "replied")) as store:
        ok, _ = nova_replies.reply_to(80, "2026-08-10 13:54")
    assert ok
    assert store.call_args[0] == (80, "2026-08-10 13:54", "Yes. Here it is.")


def test_a_missing_entry_gives_up_before_calling_the_model():
    """A card can be commented on and the entry edited away underneath it.
    Spending a CLI turn to write a reply about nothing is worse than
    silence."""
    entry, journal, comments = _sources(journal="")
    with entry, journal, comments, \
            patch.object(nova_replies, "http_json") as post, \
            patch.object(nova_replies, "add_reply") as store:
        ok, message = nova_replies.reply_to(80, "2026-08-10 13:54")
    assert not ok and "no journal entry" in message
    assert not post.called and not store.called


def test_an_entry_quoting_the_entries_marker_is_still_found_to_reply_about():
    """Same defect as the feed's, and it lands here twice: both the targeted
    single-document fetch and the whole-folder fallback hold an entries body
    with no preamble, and `parse_journal` used to cut both at the first
    `## Entries` line it saw. An entry that quotes the marker -- which this
    loop's own instructions tell every cycle to write about -- had the whole
    heading cut off the front of it, so it parsed to no entries at all and
    the reply gave up with "no journal entry" on the one card Edvard was
    actually replying to.

    Each path is starved of the other rather than just exercised, and that
    is the whole test. The first version gave both paths the entry, and
    breaking the targeted fetch failed nothing -- the fallback quietly
    answered for it, so the assertion held while the path under test was
    returning nothing at all. A rescued path is an untested path."""
    entry_md = (
        "### 2026-08-10 13:00 (Oslo) — Cycle 80\n\n"
        "I appended my captures:\n\n## Entries\n\nis the marker it needs.\n"
    )
    cases = {
        # The targeted single-document fetch, with an empty fallback under it.
        "targeted": dict(single=entry_md, journal=""),
        # The whole-folder fallback, with the targeted fetch declining.
        "fallback": dict(single=None, journal=entry_md),
    }
    for name, kwargs in cases.items():
        entry, journal, comments = _sources(**kwargs)
        with entry, journal, comments:
            found = nova_replies._entry_for(80)
        assert found is not None and found["cycle"] == 80, name
        assert "is the marker it needs." in found["body"], name


def test_a_missing_comment_gives_up_before_calling_the_model():
    entry, journal, comments = _sources()
    with entry, journal, comments, \
            patch.object(nova_replies, "http_json") as post, \
            patch.object(nova_replies, "add_reply") as store:
        ok, message = nova_replies.reply_to(80, "2026-08-10 09:00")
    assert not ok and "no comment" in message
    assert not post.called and not store.called


def test_a_bridge_error_never_reaches_the_vault():
    entry, journal, comments = _sources()
    with entry, journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(500, {"error": "boom"})), \
            patch.object(nova_replies, "add_reply") as store:
        try:
            nova_replies.reply_to(80, "2026-08-10 13:54")
        except RuntimeError as e:
            assert "bridge 500" in str(e)
        else:
            raise AssertionError("a 500 must not pass silently")
    assert not store.called


def test_an_empty_answer_is_not_stored_as_a_reply():
    """An empty `#### Nova` block would read as a reply that said nothing,
    and being written once it could never be replaced by a real one."""
    entry, journal, comments = _sources()
    with entry, journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "   "})), \
            patch.object(nova_replies, "add_reply") as store:
        try:
            nova_replies.reply_to(80, "2026-08-10 13:54")
        except RuntimeError:
            pass
        else:
            raise AssertionError("an empty answer must not be stored")
    assert not store.called


# --- the queue -------------------------------------------------------------


def _drain():
    """One turn of the real worker, synchronously.

    `nova_replies.run_once` itself, not a copy of it written here -- a copy
    would pass every mutation applied to the real one, which is the whole
    failure this indirection exists to avoid.
    """
    nova_replies.run_once()


def test_a_queued_comment_shows_as_pending_until_it_is_answered():
    with patch.object(nova_replies, "_ensure_worker"):
        assert nova_replies.enqueue(80, "2026-08-10 13:54")
        assert (80, "2026-08-10 13:54") in nova_replies.pending()
        entry, journal, comments = _sources()
        with entry, journal, comments, \
                patch.object(nova_replies, "http_json", return_value=(200, {"text": "yes"})), \
                patch.object(nova_replies, "add_reply", return_value=(True, "replied")):
            _drain()
        assert nova_replies.pending() == set()


def test_pending_clears_even_when_the_reply_fails():
    """The client polls until this goes false. If a failure left it true,
    "Nova is replying…" would sit on the card forever and the poll would
    never stop -- so the failure path is the one that matters."""
    with patch.object(nova_replies, "_ensure_worker"):
        nova_replies.enqueue(80, "2026-08-10 13:54")
        entry, journal, comments = _sources()
        with entry, journal, comments, \
                patch.object(nova_replies, "http_json", side_effect=RuntimeError("bridge down")):
            _drain()
        assert nova_replies.pending() == set()


def test_the_same_comment_is_not_queued_twice():
    """Two POSTs of the same comment, or a retry, must not spend two CLI
    turns -- and a reply is written once, so the second could not land."""
    with patch.object(nova_replies, "_ensure_worker"):
        assert nova_replies.enqueue(80, "2026-08-10 13:54") is True
        assert nova_replies.enqueue(80, "2026-08-10 13:54") is False
        assert nova_replies._queue.qsize() == 1
        _drain_pending()


def _drain_pending():
    while not nova_replies._queue.empty():
        cycle, stamp = nova_replies._queue.get()
        with nova_replies._pending_lock:
            nova_replies._pending.pop((cycle, stamp), None)
        nova_replies._queue.task_done()


def test_two_different_comments_both_queue():
    with patch.object(nova_replies, "_ensure_worker"):
        assert nova_replies.enqueue(80, "2026-08-10 13:54")
        assert nova_replies.enqueue(80, "2026-08-10 13:47")
        assert len(nova_replies.pending()) == 2
        _drain_pending()


def test_a_failed_reply_is_recorded_so_the_card_can_say_so():
    """Clearing `pending` is not enough on its own: the line simply
    disappearing is indistinguishable from an answer that never came, which
    is what Edvard reported. The failure has to survive the clear."""
    with patch.object(nova_replies, "_ensure_worker"):
        nova_replies.enqueue(80, "2026-08-10 13:54")
        entry, journal, comments = _sources()
        with entry, journal, comments, \
                patch.object(nova_replies, "http_json", side_effect=RuntimeError("bridge down")):
            _drain()
        assert nova_replies.pending() == set()
        assert "bridge down" in nova_replies.failed()[(80, "2026-08-10 13:54")]


def test_a_new_attempt_clears_the_old_failure():
    """Otherwise a card that failed once shows "couldn't answer" underneath
    a reply that did arrive on the retry."""
    with patch.object(nova_replies, "_ensure_worker"):
        nova_replies._failed[(80, "2026-08-10 13:54")] = "bridge down"
        nova_replies.enqueue(80, "2026-08-10 13:54")
        assert nova_replies.failed() == {}
        _drain_pending()


def test_pending_carries_the_time_it_was_asked_for():
    """The site needs the clock to tell "being written" from "still going"
    -- without it there is only one state and it lies. It is also what the
    card now reports: the elapsed second, with no cause named, because the
    cause is not something this side can see (issue #80)."""
    before = time.time()
    with patch.object(nova_replies, "_ensure_worker"):
        nova_replies.enqueue(80, "2026-08-10 13:54")
        asked_at = nova_replies.pending_since()[(80, "2026-08-10 13:54")]
        assert before <= asked_at <= time.time()
        _drain_pending()


# --- what the lookup costs, and where the seconds go -----------------------


def _reply_with(single=_SAME, journal=ENTRY_MD, bridge=None, unreadable=()):
    """One `reply_to(80, ...)`, with both journal sources and the bridge
    stubbed. Returns the two source mocks and the log lines it emitted."""
    entry_src, journal_src, comments = _sources(journal=journal, single=single, unreadable=unreadable)
    logged = []
    bridge = bridge or {"return_value": (200, {"text": "sure"})}
    with entry_src as entry_mock, journal_src as journal_mock, comments, \
            patch.object(nova_replies, "http_json", **bridge), \
            patch.object(nova_replies, "add_reply", return_value=(True, "replied")), \
            patch.object(nova_replies, "log", side_effect=logged.append):
        result = nova_replies.reply_to(80, "2026-08-10 13:54")
    return entry_mock, journal_mock, logged, result


def test_finding_the_entry_reads_one_document_not_the_whole_folder():
    """The reply worker wants one entry out of 103 and used to assemble and
    parse all of them to get it. Measured on the live vault 2026-08-11:
    1.496s for the folder against 0.057s for the listing plus one document,
    on every comment, growing by one entry an hour."""
    entry_mock, journal_mock, _, _ = _reply_with()
    entry_mock.assert_called_once_with(80)
    assert not journal_mock.called, "the whole journal was fetched anyway"


def test_a_partly_unreadable_folder_still_replies_when_the_entry_is_in_it():
    """The page and the reply want different things from a broken read.

    `journal_markdown` refuses a partial read outright, because it renders
    the whole feed and cannot tell a short list from a complete one. This
    caller wants one identifiable entry and can see whether it got it, so
    a chunk failure on some unrelated 2026-08-09 entry must not stop a
    reply to a comment on today's card. Raised by the reviewer on #147,
    where routing this through the refusing version did exactly that."""
    _, _, _, result = _reply_with(
        single=None,
        unreadable=["content chunk batch failed on database 'nova' (503)"],
    )
    assert result == (True, "replied")


def test_a_missing_entry_is_an_error_when_the_folder_was_only_half_read():
    """The other side of the same call, and the one that keeps it honest.

    Not finding the entry in a complete read is a fact worth stating. Not
    finding it in a read that lost a database is a guess, and returning
    None there would put "no journal entry for cycle 80" on the card about
    a cycle that may well have written one -- the same confident wrong
    answer as the empty feed this PR deleted, one page along."""
    from agora_runner import nova_sources

    with patch.object(nova_replies, "journal_entry_markdown", return_value=None), \
            patch.object(
                nova_replies, "journal_folder_best_effort",
                return_value=("### 2026-08-10 01:00 (Oslo) — Cycle 12\n\nSomeone else.", ["lost db 'nova'"]),
            ):
        with pytest.raises(RuntimeError, match="could not be fully read"):
            nova_replies._entry_for(80)
    # And with nothing lost, the same absence is reported as an absence.
    with patch.object(nova_replies, "journal_entry_markdown", return_value=None), \
            patch.object(
                nova_replies, "journal_folder_best_effort",
                return_value=("### 2026-08-10 01:00 (Oslo) — Cycle 12\n\nSomeone else.", []),
            ):
        assert nova_replies._entry_for(80) is None
    assert nova_sources.journal_folder_best_effort is not None


def test_the_whole_journal_is_still_read_when_there_is_no_entry_document():
    """The pre-2026-08-09 archive has no per-entry documents at all, and a
    tombstone or a hand-added file looks the same from here. Slow and right
    beats fast and empty -- without this the card would answer "no journal
    entry for cycle 80" for every entry written before the split."""
    entry_mock, journal_mock, _, result = _reply_with(single=None)
    entry_mock.assert_called_once_with(80)
    assert journal_mock.called
    assert result == (True, "replied")


def test_the_whole_journal_is_read_when_the_document_is_for_another_cycle():
    """The filename says `-cycle-80` and the heading inside says 79: the
    two are independent claims and only the document is authoritative.
    Answering from whatever the file happened to contain would put another
    cycle's entry in front of the model with no signal that it had."""
    wrong = ENTRY_MD.replace("Cycle 80", "Cycle 79")
    entry_mock, journal_mock, _, result = _reply_with(single=wrong)
    assert journal_mock.called
    assert result == (True, "replied")


def test_a_reply_logs_where_its_seconds_went():
    """Edvard asked for an answer within ten seconds and the honest figure
    was ten to fifteen, spread across the vault, the bridge and however many
    tools the model chose to call. A shell probe can decompose the fixed
    parts; only the real thing can see the tool calls."""
    _, _, logged, _ = _reply_with()
    line = next(l for l in logged if l.startswith("nova-reply timings"))
    for phase in ("entry=", "thread=", "bridge=", "store=", "total="):
        assert phase in line, f"{phase} missing from {line!r}"


def test_the_timings_are_logged_even_when_the_reply_fails():
    """The slow reply is the one worth measuring, and it is exactly the one
    an on-success log never prints: a bridge that gave up after queueing
    behind a 45-minute cycle emits nothing at all."""
    logged = []
    entry_src, journal_src, comments = _sources()
    with entry_src, journal_src, comments, \
            patch.object(nova_replies, "http_json", side_effect=RuntimeError("bridge down")), \
            patch.object(nova_replies, "log", side_effect=logged.append), \
            pytest.raises(RuntimeError):
        nova_replies.reply_to(80, "2026-08-10 13:54")
    line = next(l for l in logged if l.startswith("nova-reply timings"))
    assert "entry=" in line and "total=" in line
    assert "store=" not in line, "a phase that never ran should not be timed"
