"""Answering a comment on a journal card: what the model is told, and what
happens to the answer.

Two properties carry most of the weight here, and neither is about the
text of a reply -- that is the model's job and no test can pin it.

**What it is given, and what it is not.** The prompt has to contain the
entry it is answering about and the comment it is answering, because
without either the reply is invented. And the call has to go out
`restricted` and `stateless`: no tools, no session carried between
comments. A reply generated by something that could run a shell is a very
different feature from the one Edvard asked for.

**The worker never dies and never lies about being busy.** `replyPending`
is what puts "Nova is replying…" on his screen, and the client polls until
it goes false. So it has to go false on *every* path out -- a bridge
error, a vanished comment, an exception nobody predicted -- or that line
stays on the card forever and the poll never stops.
"""

import queue
import time
from unittest.mock import patch

import pytest

from agora_runner import nova_replies


@pytest.fixture(autouse=True)
def _fresh_queue():
    """The queue and the pending set are module state, so a test that left
    something in either would silently change the next one."""
    nova_replies._queue = queue.Queue()
    nova_replies._pending = {}
    nova_replies._failed = {}
    yield

ENTRY_MD = """## Entries

### 2026-08-10 13:32 (Oslo) — Cycle 80

Your idea board lost 1238 characters this morning and I put them back.

The cause was Obsidian's chunked sync, not the capture box.

---
PR: #71 | Outcome: merged
"""

THREAD_MD = """---
type: log
---

# Comments

## New

### Cycle 80 · 2026-08-10 13:54

instant replies would be cool

### Cycle 80 · 2026-08-10 13:47

did we lose any ideas?

#### Nova · 2026-08-10 13:50

No -- it came back verbatim.
"""


def _sources(journal=ENTRY_MD, comments=THREAD_MD):
    return (
        patch.object(nova_replies, "journal_markdown", return_value=journal),
        patch.object(nova_replies, "comments_markdown", return_value=comments),
    )


def _prompt_for(stamp="2026-08-10 13:54"):
    journal, comments = _sources()
    with journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "sure"})) as post, \
            patch.object(nova_replies, "add_reply", return_value=(True, "replied")):
        nova_replies.reply_to(80, stamp)
    return post.call_args[0]


# --- what the model is told ------------------------------------------------


def test_the_prompt_carries_the_entry_it_is_answering_about():
    """Without the entry the reply is invented -- this session has no memory
    of the cycle and no tool to go and look."""
    body = _prompt_for()[2]
    assert "Your idea board lost 1238 characters this morning" in body["prompt"]
    assert "PR: #71" in body["prompt"]


def test_the_prompt_carries_the_comment_being_answered():
    body = _prompt_for()[2]
    assert "instant replies would be cool" in body["prompt"]


def test_the_prompt_carries_the_rest_of_the_thread_including_earlier_replies():
    """It is a conversation on one card, so the earlier turns are context.
    They come from the file rather than from a CLI session -- the call is
    stateless, so this prompt is the only memory it has."""
    body = _prompt_for()[2]
    assert "did we lose any ideas?" in body["prompt"]
    assert "No -- it came back verbatim." in body["prompt"]


def test_the_earlier_thread_is_ordered_oldest_first_as_the_prompt_claims():
    """The prompt says "oldest first" in so many words, so the model reads
    the exchange in that order. `comments_by_cycle` now hands the thread
    over oldest-first; it used to be newest-first and this was a `reversed`.
    Two earlier comments are the minimum that can tell the two apart."""
    thread = THREAD_MD.replace(
        "### Cycle 80 · 2026-08-10 13:47",
        "### Cycle 80 · 2026-08-10 13:50\n\nand another thing\n\n### Cycle 80 · 2026-08-10 13:47",
    )
    journal, comments = _sources(comments=thread)
    with journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "sure"})) as post, \
            patch.object(nova_replies, "add_reply", return_value=(True, "replied")):
        nova_replies.reply_to(80, "2026-08-10 13:54")
    prompt = post.call_args[0][2]["prompt"]
    assert prompt.index("did we lose any ideas?") < prompt.index("and another thing")


def test_the_comment_being_answered_is_not_repeated_as_earlier_context():
    body = _prompt_for()[2]
    assert body["prompt"].count("instant replies would be cool") == 1


def test_the_system_prompt_says_it_is_not_the_session_that_did_the_work():
    """The one thing it must not do is imply a memory it does not have."""
    body = _prompt_for()[2]
    assert "NOT the session" in body["system"]


def test_the_system_prompt_names_the_pod_the_turn_actually_runs_in():
    """Measured 2026-08-11: asked which pod it ran in, the reply turn said
    `agora-persona-runner`, and reasoned its way there from "a reply turn is
    the same session as the build cycle" -- which the prompt already tells it
    is false. It runs in `nova-site` (that deployment's command is
    `run_nova_site.py`). Nothing in the prompt said so, so the model filled
    the gap and stated the guess as fact.
    """
    system = _prompt_for()[2]["system"]
    assert "`nova-site` pod" in system
    assert "not the `agora-persona-runner` pod" in system


def test_the_prompt_only_denies_pod_and_repo_tools_while_they_are_absent():
    """The prompt tells him those tools are missing because this pod holds no
    ServiceAccount token and no GitHub credentials. Grant either capability
    without moving the turn to a pod that has them and that sentence becomes
    a lie the model will repeat -- so the claim and the grant move together.
    """
    assert "kubectlRead" not in nova_replies.REPLY_CAPS
    assert "githubRead" not in nova_replies.REPLY_CAPS
    assert set(nova_replies.REPLY_CAPS) == {"vaultRead", "novaCapture"}


# --- how the call goes out -------------------------------------------------


def test_the_call_is_restricted_and_stateless():
    """`restricted` is the safety property: no shell, no vault, no GitHub,
    so the worst an HTTP POST can provoke is a paragraph. `stateless` keeps
    two comments from sharing a CLI session behind the file's back."""
    body = _prompt_for()[2]
    assert body["restricted"] is True
    assert body["stateless"] is True


def test_the_call_asks_to_run_alongside_a_cycle():
    """Without this the reply queues behind the bridge's invocation lock,
    which a Nova cycle holds for up to 45 minutes -- Edvard asked for an
    answer within ten seconds and got one forty minutes later. The bridge
    still decides: it falls back to the lock near an OAuth refresh, so
    asking is always safe and never asking is the bug."""
    body = _prompt_for()[2]
    assert body["allow_concurrent"] is True


def test_it_goes_to_the_bridge_and_so_can_only_spend_the_subscription():
    """identity.md rule 9. There is no provider to pick here and that is
    deliberate -- the bridge is the subscription, so this path cannot reach
    the metered API even by misconfiguration."""
    method, url = _prompt_for()[:2]
    assert method == "POST"
    assert url.endswith("/generate")
    assert url.startswith(nova_replies.CLAUDE_BRIDGE_URL)


def test_the_model_is_the_configured_one():
    assert _prompt_for()[2]["model"] == nova_replies.NOVA_REPLY_MODEL


# --- what happens to the answer --------------------------------------------


def test_the_answer_is_stored_against_the_comment_it_answers():
    journal, comments = _sources()
    with journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "  Yes. Here it is.  "})), \
            patch.object(nova_replies, "add_reply", return_value=(True, "replied")) as store:
        ok, _ = nova_replies.reply_to(80, "2026-08-10 13:54")
    assert ok
    assert store.call_args[0] == (80, "2026-08-10 13:54", "Yes. Here it is.")


def test_a_missing_entry_gives_up_before_calling_the_model():
    """A card can be commented on and the entry edited away underneath it.
    Spending a CLI turn to write a reply about nothing is worse than
    silence."""
    journal, comments = _sources(journal="")
    with journal, comments, \
            patch.object(nova_replies, "http_json") as post, \
            patch.object(nova_replies, "add_reply") as store:
        ok, message = nova_replies.reply_to(80, "2026-08-10 13:54")
    assert not ok and "no journal entry" in message
    assert not post.called and not store.called


def test_a_missing_comment_gives_up_before_calling_the_model():
    journal, comments = _sources()
    with journal, comments, \
            patch.object(nova_replies, "http_json") as post, \
            patch.object(nova_replies, "add_reply") as store:
        ok, message = nova_replies.reply_to(80, "2026-08-10 09:00")
    assert not ok and "no comment" in message
    assert not post.called and not store.called


def test_a_bridge_error_never_reaches_the_vault():
    journal, comments = _sources()
    with journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(500, {"error": "boom"})), \
            patch.object(nova_replies, "add_reply") as store:
        try:
            nova_replies.reply_to(80, "2026-08-10 13:54")
        except RuntimeError as e:
            assert "bridge 500" in str(e)
        else:
            raise AssertionError("a 500 must not pass silently")
    assert not store.called


def test_an_empty_answer_is_not_stored_as_a_reply():
    """An empty `#### Nova` block would read as a reply that said nothing,
    and being written once it could never be replaced by a real one."""
    journal, comments = _sources()
    with journal, comments, \
            patch.object(nova_replies, "http_json", return_value=(200, {"text": "   "})), \
            patch.object(nova_replies, "add_reply") as store:
        try:
            nova_replies.reply_to(80, "2026-08-10 13:54")
        except RuntimeError:
            pass
        else:
            raise AssertionError("an empty answer must not be stored")
    assert not store.called


# --- the queue -------------------------------------------------------------


def _drain():
    """One turn of the real worker, synchronously.

    `nova_replies.run_once` itself, not a copy of it written here -- a copy
    would pass every mutation applied to the real one, which is the whole
    failure this indirection exists to avoid.
    """
    nova_replies.run_once()


def test_a_queued_comment_shows_as_pending_until_it_is_answered():
    with patch.object(nova_replies, "_ensure_worker"):
        assert nova_replies.enqueue(80, "2026-08-10 13:54")
        assert (80, "2026-08-10 13:54") in nova_replies.pending()
        journal, comments = _sources()
        with journal, comments, \
                patch.object(nova_replies, "http_json", return_value=(200, {"text": "yes"})), \
                patch.object(nova_replies, "add_reply", return_value=(True, "replied")):
            _drain()
        assert nova_replies.pending() == set()


def test_pending_clears_even_when_the_reply_fails():
    """The client polls until this goes false. If a failure left it true,
    "Nova is replying…" would sit on the card forever and the poll would
    never stop -- so the failure path is the one that matters."""
    with patch.object(nova_replies, "_ensure_worker"):
        nova_replies.enqueue(80, "2026-08-10 13:54")
        journal, comments = _sources()
        with journal, comments, \
                patch.object(nova_replies, "http_json", side_effect=RuntimeError("bridge down")):
            _drain()
        assert nova_replies.pending() == set()


def test_the_same_comment_is_not_queued_twice():
    """Two POSTs of the same comment, or a retry, must not spend two CLI
    turns -- and a reply is written once, so the second could not land."""
    with patch.object(nova_replies, "_ensure_worker"):
        assert nova_replies.enqueue(80, "2026-08-10 13:54") is True
        assert nova_replies.enqueue(80, "2026-08-10 13:54") is False
        assert nova_replies._queue.qsize() == 1
        _drain_pending()


def _drain_pending():
    while not nova_replies._queue.empty():
        cycle, stamp = nova_replies._queue.get()
        with nova_replies._pending_lock:
            nova_replies._pending.pop((cycle, stamp), None)
        nova_replies._queue.task_done()


def test_two_different_comments_both_queue():
    with patch.object(nova_replies, "_ensure_worker"):
        assert nova_replies.enqueue(80, "2026-08-10 13:54")
        assert nova_replies.enqueue(80, "2026-08-10 13:47")
        assert len(nova_replies.pending()) == 2
        _drain_pending()


def test_a_failed_reply_is_recorded_so_the_card_can_say_so():
    """Clearing `pending` is not enough on its own: the line simply
    disappearing is indistinguishable from an answer that never came, which
    is what Edvard reported. The failure has to survive the clear."""
    with patch.object(nova_replies, "_ensure_worker"):
        nova_replies.enqueue(80, "2026-08-10 13:54")
        journal, comments = _sources()
        with journal, comments, \
                patch.object(nova_replies, "http_json", side_effect=RuntimeError("bridge down")):
            _drain()
        assert nova_replies.pending() == set()
        assert "bridge down" in nova_replies.failed()[(80, "2026-08-10 13:54")]


def test_a_new_attempt_clears_the_old_failure():
    """Otherwise a card that failed once shows "couldn't answer" underneath
    a reply that did arrive on the retry."""
    with patch.object(nova_replies, "_ensure_worker"):
        nova_replies._failed[(80, "2026-08-10 13:54")] = "bridge down"
        nova_replies.enqueue(80, "2026-08-10 13:54")
        assert nova_replies.failed() == {}
        _drain_pending()


def test_pending_carries_the_time_it_was_asked_for():
    """The site needs the clock to tell "being written" from "queued behind
    a cycle" -- without it there is only one state and it lies."""
    before = time.time()
    with patch.object(nova_replies, "_ensure_worker"):
        nova_replies.enqueue(80, "2026-08-10 13:54")
        asked_at = nova_replies.pending_since()[(80, "2026-08-10 13:54")]
        assert before <= asked_at <= time.time()
        _drain_pending()
