"""A held-out set of this loop's own past failures, run against the current code.

    python3 -m tools.regression_gate

**Exit 2 means a past failure has come back**, 1 means a check could not
read what it needs (which never reads as clean), 0 means every failure in
the corpus is still fixed and the report names the ones it checked.

Idea #88 on the owner's board is a criticism of me and it is correct:
*"every number I use to justify rewriting my own constitution is generated
by the thing being measured"*. Cycle 336 measured the expensive answer to
it -- one Terminal-Bench 2.0 run is roughly 58% of a seven-day quota
window, and the method that made it interesting runs the benchmark twice
per iteration for five to seven iterations -- and closed that instrument.
What that cycle left open is the cheap half, in its own words:

> I write one candidate fix and merge it because it sounds right, with no
> held-out set that could reject it. A no-regression gate built from
> failures already in this journal is one cycle's work and is external in
> the only sense that matters -- those failures were not generated by the
> change being judged.

This is that gate. It is **not** a benchmark and does not pretend to be a
score. It is a list of specific things that went wrong, each with the cycle
that found it, and a check that would have caught it. A change that makes
one of these go red is reintroducing a failure this loop has already paid
for once.

**Why this is not detector number four.** `prompt.md` warns that three
fixes of the same shape means the shape is the bug, and this repo already
has `doc_integrity`, `sync_contract` and `lint_entry`, each a module built
around one class of failure. The difference is that those own a *problem*
and this owns a *record*: adding a past failure here is one entry in
`CORPUS` at the bottom of this file, not a new module, so the thing that
grows is a list and not a surface. When a cycle finds a real regression
risk in a fix it is about to merge, the entry belongs here.

**Two surfaces, and they are not equally strong.** Most checks drive the
shipped code and assert on what it does; those say `drove the code` in the
report. Two read a vault document and assert on its text, because the
failure was in an instruction rather than in a function -- those say `read
the text` and are weaker by exactly as much as a grep is weaker than a
call. Both are labelled in the output rather than blended, because a
report that hides which of its rows is a grep is the same overclaiming
`personality.md` has a section about.

**Every check is two-sided.** A check that only asserts the bad input is
refused would still pass if the code refused everything, and a test whose
negative result is guaranteed in advance is not evidence -- `prompt.md`
says so about `agents-limits` and it applies to my own tests. So each
behavioural check also asserts the *good* input is accepted, in the same
call, and reports a regression if either half moves.

**Run this as a CLI, never inside the serving process.** Two of the
behavioural checks swap a module-level function for a stub and put it back
in a `finally` -- `reply.claude_cli_generate` and `nova_site.comment_on_row`.
That is safe in a one-shot process and is a real hazard in a threaded server,
where a live request could land on the stub during the swap. Nothing imports
this module today; the sentence is here so nothing starts.

The vault is read through `/app/bridge/vault_tool.py` when that exists
(the bridge pod) and through `agora_runner.vault` otherwise (the runner
pod). When neither answers, the check reports `UNREADABLE` and the run
exits 1 -- the same contract as `security_alerts` and `agentic_health`,
for the same reason: an instrument that cannot see must not report clean.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent

BRIDGE_VAULT = Path("/app/bridge/vault_tool.py")


class Unreadable(Exception):
    """A check could not reach what it needs. Never reads as clean."""


def read_vault(path: str) -> str:
    """One vault document as text, from whichever pod this is.

    Raises `Unreadable` rather than returning an empty string, because an
    empty document and an unreachable one mean opposite things and every
    textual check below would call the empty one clean.
    """
    if BRIDGE_VAULT.exists():
        proc = subprocess.run(
            [sys.executable, str(BRIDGE_VAULT), "get", path],
            capture_output=True, text=True, timeout=120,
        )
        if proc.returncode != 0:
            raise Unreadable((proc.stderr or proc.stdout or "").strip()[:200] or "vault_tool exited nonzero")
        body = proc.stdout
        if not body.strip() or body.strip() == "[not found]":
            raise Unreadable(f"{path} came back empty or not found")
        return body
    try:
        from agora_runner.vault import VaultClient  # type: ignore
    except Exception as e:  # pragma: no cover - depends on the pod
        raise Unreadable(f"no vault client here: {e}")
    try:
        body = VaultClient().get(path)
    except Exception as e:
        raise Unreadable(str(e)[:200])
    if not body or not body.strip():
        raise Unreadable(f"{path} came back empty")
    return body


@dataclass(frozen=True)
class Regression:
    """One failure this loop already made, and the check that catches it.

    `failure` is what actually went wrong, in one sentence, written for
    someone who was not there. `cycle` and `date` are the receipt -- a
    corpus entry with no incident behind it is an opinion, and opinions
    belong in `prompt.md` where they can be argued with.
    """

    slug: str
    cycle: str
    date: str
    surface: str  # "drove the code" | "read the text"
    failure: str
    check: Callable[[], Optional[str]]


# ---------------------------------------------------------------------------
# The checks. Each returns None when the failure is still fixed, or a
# sentence describing what it saw when it is not.
# ---------------------------------------------------------------------------


def _check_unattended_metered() -> Optional[str]:
    from agora_runner import reply as reply_mod

    persona = {"model": "anthropic:claude-sonnet-5", "thinking": False}
    history = [{"role": "user", "content": "hi"}]

    try:
        reply_mod.generate_reply(persona, {}, "s", history, "conv-1", unattended=True)
    except reply_mod.MeteredProviderBlocked:
        pass
    except Exception as e:
        return (f"an unattended turn on 'anthropic:' raised {type(e).__name__} instead of "
                f"MeteredProviderBlocked ({e}) -- the guard is not the thing refusing it")
    else:
        return "an unattended turn on a metered provider was allowed through"

    # The other side: the guard must not be refusing everything. The same
    # unattended turn on the subscription provider has to reach the model.
    # Stubbed rather than really dispatched -- a check that phones a model to
    # prove a guard let it through is a check nobody will run every cycle.
    original = reply_mod.claude_cli_generate
    reached = []
    try:
        reply_mod.claude_cli_generate = lambda *a, **k: reached.append(a)
        reply_mod.generate_reply(dict(persona, model="claude-cli:claude-sonnet-5"), {}, "s",
                                 history, "conv-1", unattended=True)
    except reply_mod.MeteredProviderBlocked:
        return ("the guard also refuses 'claude-cli:', which is the subscription provider -- "
                "it would block every unattended turn, so its refusal proves nothing")
    except Exception as e:
        return f"the subscription path raised {type(e).__name__} before reaching the model: {e}"
    finally:
        reply_mod.claude_cli_generate = original
    if not reached:
        return ("an unattended subscription turn never reached the model, so the refusal above "
                "is refusing something other than the metered provider")
    return None


def _check_ask_opens_with_a_question() -> Optional[str]:
    from tools import lint_entry

    statement = ("**Needs input:** The status circles are hard to read on a phone and I would "
                 "like to change them. Should they become words?\n")
    question = ("**Needs input:** Yes or no, should the status circles become words like the "
                "priorities did? They are hard to read on a phone.\n")

    if lint_entry._ask_question_finding(statement) is None:
        return "an ask whose first sentence is a statement was accepted"
    if lint_entry._ask_question_finding(question) is not None:
        return "an ask that does open with a question was refused -- the check refuses everything"
    return None


def _check_security_sweep_covers_the_org() -> Optional[str]:
    """Does the advisory sweep still union the org in, or only the checkouts?

    **Both halves are stubbed on purpose.** The first version of this check
    called the real `_repos_from_workspace()`, so it passed on my pod and
    went red in CI, where there are no checkouts at all -- no checkout means
    no org to enumerate, so the fake listing below was never consulted and
    the check reported Cycle 432's blind spot against code that does not
    have it. A check whose verdict moves with the environment is not a check
    of the code, and a gate that cries regression on a clean tree is worse
    than no gate. So the workspace is fixed here too.
    """
    from tools import security_alerts

    outsider = "SokratesAI/a-repo-with-no-checkout-here"
    checkouts = (["SokratesAI/agora-persona-runner"], [])

    def fake_gh(args):
        return 0, json.dumps([
            {"nameWithOwner": outsider, "isArchived": False},
            {"nameWithOwner": "SokratesAI/an-archived-one", "isArchived": True},
        ]), ""

    original_workspace = security_alerts._repos_from_workspace
    try:
        security_alerts._repos_from_workspace = lambda: checkouts
        repos, _unplaceable, _notes, incomplete = security_alerts._repos_to_sweep(run=fake_gh)
        broken = security_alerts._repos_to_sweep(run=lambda args: (1, "", "gh: could not resolve org"))
    finally:
        security_alerts._repos_from_workspace = original_workspace
    incomplete_when_broken = broken[3]

    if outsider not in repos:
        return ("a repo the org lists but this loop has not cloned was left out of the sweep -- "
                "this is Cycle 432's blind spot exactly")
    if "SokratesAI/an-archived-one" in repos:
        return "an archived repo was swept; an alert there cannot be closed by a pull request"

    # Two-sided: a failure to list the org must not read as a clean sweep.
    if not incomplete_when_broken:
        return "an org that could not be listed was reported as a complete sweep"
    if incomplete:
        return "a healthy org listing was reported as incomplete -- the flag is stuck on"
    return None


def _check_board_comment_names_its_author() -> Optional[str]:
    from agora_runner import nova_site

    class Stub:
        def __init__(self):
            self.sent = []

        def _send_json(self, status, body):
            self.sent.append((status, body))

    payload = {"target": "ideas", "number": 38, "text": "one line, no break"}

    stub = Stub()
    nova_site.NovaSiteHandler._post_board_comment(stub, dict(payload))
    if not stub.sent or stub.sent[0][0] != 400:
        return (f"a board comment with no author was not refused (got {stub.sent!r}) -- "
                "Cycle 479's two notes landed on the owner's board signed with his name")

    # Two-sided: a named author has to get past that check, or the refusal
    # above says nothing about the author field at all.
    original = nova_site.comment_on_row
    reached = []
    try:
        nova_site.comment_on_row = lambda *a, **k: (reached.append(a) or (False, "stubbed"))
        stub2 = Stub()
        try:
            nova_site.NovaSiteHandler._post_board_comment(stub2, dict(payload, author="Nova"))
        except Exception:
            # Whatever the route does *after* the writer is not this check's
            # business -- `reached` is appended inside the writer itself, so it
            # already records that the author check let this call through.
            pass
    finally:
        nova_site.comment_on_row = original
    if not reached:
        return ("a board comment naming 'Nova' as its author never reached the writer, so the "
                "refusal above is refusing something other than a missing author")
    return None


def _check_prompt_sweeps_every_namespace() -> Optional[str]:
    body = read_vault("projects/sokrates/projects/agora/nova/resources/prompt.md")
    if "kubectl get pods -A" not in body:
        return ("step 1's pod sweep no longer says `kubectl get pods -A` -- it read `-n agents` "
                "until Cycle 449, and a pod in `infra` crash-looped for 37 hours unseen")
    return None


def _check_prompt_does_not_hardcode_the_shared_checkout() -> Optional[str]:
    body = read_vault("projects/sokrates/projects/agora/nova/resources/prompt.md")
    bad = [line.strip() for line in body.splitlines()
           if "cd /data/workspace/" in line or line.strip().startswith("cd /data/workspace ")]
    if bad:
        return ("a command in prompt.md `cd`s straight into the shared checkout instead of "
                f"${{NOVA_WORKSPACE:-/data/workspace}}: {bad[0][:120]!r} -- concurrent cycles "
                "share that directory and would write over each other")
    return None


def _check_digest_roll_reads_the_whole_document() -> Optional[str]:
    """A spliced live digest must be refused before the roll, not after.

    Cycle 492 wrote `journal-digest.md` carrying two `## Needs input` and two
    `## Next cycle` sections, one block stacked under the other.
    `tools.roll_digest` read those exact bytes out of the vault seconds later
    and said nothing, because every check it carries reasons about the
    `## Digest` section `plan` splits out and the damage was above it. The
    site hid it too -- `parse_digest` keeps the last section of each name --
    so the only reader who saw it was the owner, in Obsidian.
    """
    from tools import roll_digest
    from tools.rolling import RollError

    head = "---\ntype: log\n---\n\n# Journal — Digest\n"
    tail = "\n## Digest\n\n**Cycle 2** (2026-08-26 19:14) — Second.\n\n**Cycle 1** (2026-08-26 18:36) — First.\n"
    spliced = head + "\n## Next cycle\n\nStale.\n\n## Next cycle\n\nCurrent.\n" + tail
    whole = head + "\n## Next cycle\n\nOnly one.\n" + tail

    try:
        roll_digest.plan(spliced, "", keep=1)
    except RollError as exc:
        if "duplicated heading" not in str(exc):
            return f"roll_digest refused a spliced digest for the wrong reason: {exc}"
    else:
        return "roll_digest rolled a digest holding two '## Next cycle' sections"

    # Two-sided: a checker that refuses everything would pass the half above
    # while making every honest digest unrollable.
    try:
        roll_digest.plan(whole, "", keep=1)
    except RollError as exc:
        return f"roll_digest refused an undamaged digest: {exc}"
    return None


def _check_ci_health_ignores_an_abandoned_run() -> Optional[str]:
    """A queued run that later runs have overtaken must not read as a live stall.

    Measured Cycle 495, 2026-08-26 20:04 Oslo: run 32984347949 was created four
    seconds into that afternoon's Actions outage and was still `queued` with
    zero jobs three hours later — three minutes after githubstatus resolved the
    incident, with its own pull request merged and eight later runs in the same
    repo finished. `ci_health` read `operational` off the status page and still
    said a merge could not complete, off that orphan alone. Nothing removes an
    abandoned run from a queue, so that verdict had no end date.
    """
    import json
    import subprocess
    from tools import ci_health

    class _Resp:
        def __init__(self, body):
            self._body = body.encode()

        def read(self):
            return self._body

        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

    def opener(request, timeout=None):
        return _Resp(json.dumps({
            "components": [{"name": "Actions", "status": "operational"}],
            "incidents": []}))

    def gh_with_completed_at(stamp):
        def gh(cmd, **kwargs):
            path = cmd[2]
            if "/jobs" in path:
                return subprocess.CompletedProcess(cmd, 0, stdout="0", stderr="")
            if "status=completed" in path:
                body = [] if stamp is None else [{"id": 2, "created_at": stamp}]
                return subprocess.CompletedProcess(cmd, 0, stdout=json.dumps(body), stderr="")
            if "/commits" in path:
                return subprocess.CompletedProcess(cmd, 0, stdout=json.dumps([]), stderr="")
            return subprocess.CompletedProcess(cmd, 0, stdout=json.dumps([{
                "id": 1, "name": "build", "status": "queued", "head_branch": "b",
                "created_at": "2000-01-01T00:00:00Z"}]), stderr="")
        return gh

    status, lines = ci_health.check(opener=opener,
                                    run=gh_with_completed_at("2000-01-01T01:00:00Z"),
                                    repos=["Org/repo"])
    if status != 0 or not any(l.startswith("ABANDONED") for l in lines):
        return ("ci_health called a merge impossible on a queued run that a later run had "
                f"already overtaken (exit {status}) -- an orphan from an outage that has since "
                "resolved would have refused every merge after it, forever")

    # Two-sided: with nothing completed after it, the stall must still stand,
    # or the check above only proves the tool stopped reporting stalls at all.
    status, lines = ci_health.check(opener=opener, run=gh_with_completed_at(None),
                                    repos=["Org/repo"])
    if status != 2 or not any(l.startswith("STALLED") for l in lines):
        return ("ci_health quietened a zero-job run with no completed run after it to "
                f"compare against (exit {status}) -- nothing measured, nothing to quieten")
    return None


def _check_ci_health_separates_the_two_causes() -> Optional[str]:
    """A GitHub-side outage and a run of ours creating no jobs must stay two lines.

    Cycle 487 read a run queued fourteen minutes with zero jobs as the Actions
    billing block, because that is the failure this loop remembers. It was a
    GitHub-side outage opened four seconds after the run was created, and the
    two have opposite conclusions -- "wait, then merge" against "nothing merges
    until September and the owner has to act".
    """
    import json
    import subprocess
    import urllib.error
    from tools import ci_health

    class _Resp:
        def __init__(self, body):
            self._body = body.encode()

        def read(self):
            return self._body

        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

    def opener_for(actions):
        def opener(request, timeout=None):
            return _Resp(json.dumps({
                "components": [{"name": "Actions", "status": actions}],
                "incidents": [{"name": "Incident with Actions"}] if actions != "operational" else [],
            }))
        return opener

    def gh(cmd, **kwargs):
        path = cmd[2]
        if "/jobs" in path:
            return subprocess.CompletedProcess(cmd, 0, stdout="0", stderr="")
        return subprocess.CompletedProcess(cmd, 0, stdout=json.dumps([{
            "id": 1, "name": "build", "status": "queued", "head_branch": "b",
            "created_at": "2000-01-01T00:00:00Z"}]), stderr="")

    status, lines = ci_health.check(opener=opener_for("major_outage"), run=gh,
                                    repos=["Org/repo"])
    github_side = [l for l in lines if l.startswith("GITHUB-SIDE")]
    stalled = [l for l in lines if l.startswith("STALLED")]
    if status != 2 or len(github_side) != 1 or len(stalled) != 1:
        return ("ci_health merged the GitHub-side outage and the zero-job run into one "
                f"verdict (exit {status}, {len(github_side)} outage line(s), "
                f"{len(stalled)} stalled line(s)) -- Cycle 487 chased the wrong cause")

    # Two-sided: with GitHub healthy the stalled line must survive on its own,
    # or the check above is only reading the status page.
    status, lines = ci_health.check(opener=opener_for("operational"), run=gh,
                                    repos=["Org/repo"])
    if status != 2 or not any(l.startswith("STALLED") for l in lines):
        return ("ci_health stopped reporting a run of ours that created zero jobs once "
                f"githubstatus said Actions was operational (exit {status}) -- that is the "
                "billing-block shape, which githubstatus never reports")
    return None


def _check_name_guard_sees_an_unstaged_file() -> Optional[str]:
    """The owner's-name guard must read the files a commit will carry, not only the tracked ones.

    Cycle 488 added `tools/ci_health.py` with his name in its opening
    docstring, ran the suite before committing, and recorded "green locally"
    honestly. The suite really was green: the guard built its file list from
    `git ls-files`, which lists only what is *already tracked*, so the one new
    module it needed to read was the one file it could not see. CI staged it
    and turned red. That is a positive result guaranteed in advance, aimed
    precisely at the case the guard exists for.

    Two-sided on purpose: an unstaged file must be in the list, and an ignored
    one must not -- a version that returned every path on the disk would pass
    the first half and drag `node_modules` in behind it.
    """
    from tools import name_scan

    root = Path(__file__).resolve().parent.parent
    probe = root / "_regression_gate_unstaged_probe.py"
    ignored = root / "__pycache__" / "_regression_gate_ignored_probe.py"
    ignored.parent.mkdir(exist_ok=True)
    probe.write_text('"""Edvard wrote this and never staged it."""\n')
    ignored.write_text('"""Edvard, in a path .gitignore covers."""\n')
    try:
        try:
            files = name_scan.repo_files(root)
        except Exception as exc:  # noqa: BLE001 -- an unreadable tree is a failure here
            return f"could not list the working tree: {exc}"
        if probe.name not in files:
            return "a file that is not staged yet is invisible to the name guard"
        if f"__pycache__/{ignored.name}" in files:
            return "the name guard is reading files git is told to ignore"
        if not name_scan.scan([str(probe)]):
            return "the scan does not flag the owner's name in an unstaged docstring"
    finally:
        probe.unlink()
        ignored.unlink()
    return None


CORPUS = [
    Regression(
        slug="name-guard-blind-to-an-unstaged-file",
        cycle="466 and 488",
        date="2026-08-26",
        surface="drove the code",
        failure=("The guard keeping the owner's name out of this public repo built its file "
                 "list from `git ls-files`, so a module a cycle had just written was the one "
                 "file it could not read. Cycle 466 hit it, filed a note saying to run "
                 "`git add` before the last local run, and 22 cycles later Cycle 488 hit the "
                 "identical failure on a different new module. A note did not stop it twice; "
                 "this entry is here because the code now does."),
        check=_check_name_guard_sees_an_unstaged_file,
    ),
    Regression(
        slug="digest-rolled-a-spliced-document",
        cycle="492",
        date="2026-08-26",
        surface="drove the code",
        failure=("The digest went live with the previous cycle's **Needs input** and "
                 "**Next cycle** blocks still above the current one's. `roll_digest` read "
                 "the damaged file out of the vault seconds after it was written and "
                 "rolled it happily, because every check it had reasoned about the "
                 "`## Digest` section alone. The site rendered the last section of each "
                 "name and hid it; Obsidian, which the owner reads, showed both."),
        check=_check_digest_roll_reads_the_whole_document,
    ),
    Regression(
        slug="an-abandoned-run-read-as-a-live-stall",
        cycle="495",
        date="2026-08-26",
        surface="drove the code",
        failure=("A run created four seconds into an Actions outage was still `queued` with "
                 "zero jobs three minutes after that incident resolved, with its pull "
                 "request merged and eight later runs finished. `ci_health` read "
                 "`operational` off the status page and still printed \"a merge cannot "
                 "complete right now\" off that one orphan — and nothing removes an "
                 "abandoned run from a queue, so the verdict had no end date. A queued run "
                 "outlives the thing that queued it; the queue alone cannot tell a scar "
                 "from a symptom."),
        check=_check_ci_health_ignores_an_abandoned_run,
    ),
    Regression(
        slug="a-queued-run-read-as-a-billing-block",
        cycle="487",
        date="2026-08-26",
        surface="drove the code",
        failure=("A build sat queued fourteen minutes having created zero jobs, and I wrote "
                 "into the handoff that it looked like the Actions billing block. It was a "
                 "GitHub-side Actions outage opened four seconds after the run was created. "
                 "The two causes have opposite conclusions and one verdict line cannot carry "
                 "both."),
        check=_check_ci_health_separates_the_two_causes,
    ),
    Regression(
        slug="unattended-metered-provider",
        cycle="78",
        date="2026-08-10",
        surface="drove the code",
        failure=("A scheduled turn could run on the raw `anthropic:` API and spend the owner's "
                 "prepaid balance forever with nobody watching. His hard rule against it lived "
                 "only in a markdown file until this guard was written."),
        check=_check_unattended_metered,
    ),
    Regression(
        slug="board-comment-with-no-author",
        cycle="479",
        date="2026-08-26",
        surface="drove the code",
        failure=("The board-comment endpoint defaulted the author to the owner, so two notes I "
                 "posted from a shell landed on his live board signed with his name -- and then "
                 "set the unanswered-comment flag that outranks a 🔴, on a question he never asked."),
        check=_check_board_comment_names_its_author,
    ),
    Regression(
        slug="security-sweep-covered-only-the-checkouts",
        cycle="432",
        date="2026-08-25",
        surface="drove the code",
        failure=("The advisory sweep read only the repos this loop happens to clone, so it "
                 "printed 'nothing to act on' while sokrates-docs carried six open Dependabot "
                 "alerts, four of them high."),
        check=_check_security_sweep_covers_the_org,
    ),
    Regression(
        slug="an-ask-that-opens-with-a-statement",
        cycle="273",
        date="2026-08-20",
        surface="drove the code",
        failure=("A **Needs input** block spent 35 words on context before its first full stop, "
                 "so the owner had to mine a wall of text for the question. Six of the eight "
                 "asks written up to that morning opened with a statement."),
        check=_check_ask_opens_with_a_question,
    ),
    Regression(
        slug="pod-sweep-narrowed-to-one-namespace",
        cycle="449",
        date="2026-08-25",
        surface="read the text",
        failure=("The opening pod check said `-n agents`, so `whatsapp-bridge` crash-looped in "
                 "`infra` for 37 hours with 314 restarts while every cycle read a clean list."),
        check=_check_prompt_sweeps_every_namespace,
    ),
    Regression(
        slug="hardcoded-shared-checkout",
        cycle="≈460",
        date="2026-08-25",
        surface="read the text",
        failure=("Commands hardcoded `/data/workspace`, which is the shared checkout. Once "
                 "cycles began overlapping, two of them writing there at once would clobber "
                 "each other's working tree."),
        check=_check_prompt_does_not_hardcode_the_shared_checkout,
    ),
]


def run(corpus=None):
    """`(rows, status)` -- every entry checked, and the exit code to use."""
    rows, status = [], 0
    for item in corpus if corpus is not None else CORPUS:
        try:
            finding = item.check()
        except Unreadable as e:
            rows.append((item, "UNREADABLE", str(e)))
            status = max(status, 1)
            continue
        except Exception as e:  # a check that crashes has not said the failure is fixed
            rows.append((item, "UNREADABLE", f"the check itself raised {type(e).__name__}: {e}"))
            status = max(status, 1)
            continue
        if finding:
            rows.append((item, "REGRESSED", finding))
            status = 2
        else:
            rows.append((item, "held", ""))
    return rows, status


def format_report(rows, status):
    lines = []
    for item, verdict, detail in rows:
        if verdict == "held":
            lines.append(f"held        {item.slug}  (cycle {item.cycle}, {item.date}; {item.surface})")
        else:
            lines.append(f"{verdict}  {item.slug}  (cycle {item.cycle}, {item.date}; {item.surface})")
            lines.append(f"      what went wrong then: {item.failure}")
            lines.append(f"      what I see now: {detail}")
    lines.append(f"Checked {len(rows)} past failure(s) from this loop's own journal.")
    if status == 2:
        lines.append("A failure this loop already paid for once is back. Do not merge over this.")
    elif status == 1:
        lines.append("At least one check could not read what it needs, so this is not a clean run.")
    else:
        lines.append("Every past failure in the corpus is still fixed.")
    return "\n".join(lines)


def main(argv=None):
    rows, status = run()
    print(format_report(rows, status))
    return status


if __name__ == "__main__":
    raise SystemExit(main())
