"""A held-out set of this loop's own past failures, run against the current code.

    python3 -m tools.regression_gate

**Exit 2 means a past failure has come back**, 1 means a check could not
read what it needs (which never reads as clean), 0 means every failure in
the corpus is still fixed and the report names the ones it checked.

Idea #88 on the owner's board is a criticism of me and it is correct:
*"every number I use to justify rewriting my own constitution is generated
by the thing being measured"*. Cycle 336 measured the expensive answer to
it -- one Terminal-Bench 2.0 run is roughly 58% of a seven-day quota
window, and the method that made it interesting runs the benchmark twice
per iteration for five to seven iterations -- and closed that instrument.
What that cycle left open is the cheap half, in its own words:

> I write one candidate fix and merge it because it sounds right, with no
> held-out set that could reject it. A no-regression gate built from
> failures already in this journal is one cycle's work and is external in
> the only sense that matters -- those failures were not generated by the
> change being judged.

This is that gate. It is **not** a benchmark and does not pretend to be a
score. It is a list of specific things that went wrong, each with the cycle
that found it, and a check that would have caught it. A change that makes
one of these go red is reintroducing a failure this loop has already paid
for once.

**Why this is not detector number four.** `prompt.md` warns that three
fixes of the same shape means the shape is the bug, and this repo already
has `doc_integrity`, `sync_contract` and `lint_entry`, each a module built
around one class of failure. The difference is that those own a *problem*
and this owns a *record*: adding a past failure here is one entry in
`CORPUS` at the bottom of this file, not a new module, so the thing that
grows is a list and not a surface. When a cycle finds a real regression
risk in a fix it is about to merge, the entry belongs here.

**Two surfaces, and they are not equally strong.** Most checks drive the
shipped code and assert on what it does; those say `drove the code` in the
report. Two read a vault document and assert on its text, because the
failure was in an instruction rather than in a function -- those say `read
the text` and are weaker by exactly as much as a grep is weaker than a
call. Both are labelled in the output rather than blended, because a
report that hides which of its rows is a grep is the same overclaiming
`personality.md` has a section about.

**Every check is two-sided.** A check that only asserts the bad input is
refused would still pass if the code refused everything, and a test whose
negative result is guaranteed in advance is not evidence -- `prompt.md`
says so about `agents-limits` and it applies to my own tests. So each
behavioural check also asserts the *good* input is accepted, in the same
call, and reports a regression if either half moves.

The vault is read through `/app/bridge/vault_tool.py` when that exists
(the bridge pod) and through `agora_runner.vault` otherwise (the runner
pod). When neither answers, the check reports `UNREADABLE` and the run
exits 1 -- the same contract as `security_alerts` and `agentic_health`,
for the same reason: an instrument that cannot see must not report clean.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent

BRIDGE_VAULT = Path("/app/bridge/vault_tool.py")


class Unreadable(Exception):
    """A check could not reach what it needs. Never reads as clean."""


def read_vault(path: str) -> str:
    """One vault document as text, from whichever pod this is.

    Raises `Unreadable` rather than returning an empty string, because an
    empty document and an unreachable one mean opposite things and every
    textual check below would call the empty one clean.
    """
    if BRIDGE_VAULT.exists():
        proc = subprocess.run(
            [sys.executable, str(BRIDGE_VAULT), "get", path],
            capture_output=True, text=True, timeout=120,
        )
        if proc.returncode != 0:
            raise Unreadable((proc.stderr or proc.stdout or "").strip()[:200] or "vault_tool exited nonzero")
        body = proc.stdout
        if not body.strip() or body.strip() == "[not found]":
            raise Unreadable(f"{path} came back empty or not found")
        return body
    try:
        from agora_runner.vault import VaultClient  # type: ignore
    except Exception as e:  # pragma: no cover - depends on the pod
        raise Unreadable(f"no vault client here: {e}")
    try:
        body = VaultClient().get(path)
    except Exception as e:
        raise Unreadable(str(e)[:200])
    if not body or not body.strip():
        raise Unreadable(f"{path} came back empty")
    return body


@dataclass(frozen=True)
class Regression:
    """One failure this loop already made, and the check that catches it.

    `failure` is what actually went wrong, in one sentence, written for
    someone who was not there. `cycle` and `date` are the receipt -- a
    corpus entry with no incident behind it is an opinion, and opinions
    belong in `prompt.md` where they can be argued with.
    """

    slug: str
    cycle: str
    date: str
    surface: str  # "drove the code" | "read the text"
    failure: str
    check: Callable[[], Optional[str]]


# ---------------------------------------------------------------------------
# The checks. Each returns None when the failure is still fixed, or a
# sentence describing what it saw when it is not.
# ---------------------------------------------------------------------------


def _check_unattended_metered() -> Optional[str]:
    from agora_runner import reply as reply_mod

    persona = {"model": "anthropic:claude-sonnet-5", "thinking": False}
    history = [{"role": "user", "content": "hi"}]

    try:
        reply_mod.generate_reply(persona, {}, "s", history, "conv-1", unattended=True)
    except reply_mod.MeteredProviderBlocked:
        pass
    except Exception as e:
        return (f"an unattended turn on 'anthropic:' raised {type(e).__name__} instead of "
                f"MeteredProviderBlocked ({e}) -- the guard is not the thing refusing it")
    else:
        return "an unattended turn on a metered provider was allowed through"

    # The other side: the guard must not be refusing everything. The same
    # unattended turn on the subscription provider has to reach the model.
    # Stubbed rather than really dispatched -- a check that phones a model to
    # prove a guard let it through is a check nobody will run every cycle.
    original = reply_mod.claude_cli_generate
    reached = []
    try:
        reply_mod.claude_cli_generate = lambda *a, **k: reached.append(a)
        reply_mod.generate_reply(dict(persona, model="claude-cli:claude-sonnet-5"), {}, "s",
                                 history, "conv-1", unattended=True)
    except reply_mod.MeteredProviderBlocked:
        return ("the guard also refuses 'claude-cli:', which is the subscription provider -- "
                "it would block every unattended turn, so its refusal proves nothing")
    except Exception as e:
        return f"the subscription path raised {type(e).__name__} before reaching the model: {e}"
    finally:
        reply_mod.claude_cli_generate = original
    if not reached:
        return ("an unattended subscription turn never reached the model, so the refusal above "
                "is refusing something other than the metered provider")
    return None


def _check_ask_opens_with_a_question() -> Optional[str]:
    from tools import lint_entry

    statement = ("**Needs input:** The status circles are hard to read on a phone and I would "
                 "like to change them. Should they become words?\n")
    question = ("**Needs input:** Yes or no, should the status circles become words like the "
                "priorities did? They are hard to read on a phone.\n")

    if lint_entry._ask_question_finding(statement) is None:
        return "an ask whose first sentence is a statement was accepted"
    if lint_entry._ask_question_finding(question) is not None:
        return "an ask that does open with a question was refused -- the check refuses everything"
    return None


def _check_security_sweep_covers_the_org() -> Optional[str]:
    from tools import security_alerts

    outsider = "SokratesAI/a-repo-with-no-checkout-here"

    def fake_gh(args):
        return 0, json.dumps([
            {"nameWithOwner": outsider, "isArchived": False},
            {"nameWithOwner": "SokratesAI/an-archived-one", "isArchived": True},
        ]), ""

    repos, _unplaceable, _notes, incomplete = security_alerts._repos_to_sweep(run=fake_gh)
    if outsider not in repos:
        return ("a repo the org lists but this loop has not cloned was left out of the sweep -- "
                "this is Cycle 432's blind spot exactly")
    if "SokratesAI/an-archived-one" in repos:
        return "an archived repo was swept; an alert there cannot be closed by a pull request"

    # Two-sided: a failure to list the org must not read as a clean sweep.
    def broken_gh(args):
        return 1, "", "gh: could not resolve org"

    _r, _u, _n, incomplete_when_broken = security_alerts._repos_to_sweep(run=broken_gh)
    if not incomplete_when_broken:
        return "an org that could not be listed was reported as a complete sweep"
    if incomplete:
        return "a healthy org listing was reported as incomplete -- the flag is stuck on"
    return None


def _check_board_comment_names_its_author() -> Optional[str]:
    from agora_runner import nova_site

    class Stub:
        def __init__(self):
            self.sent = []

        def _send_json(self, status, body):
            self.sent.append((status, body))

    payload = {"target": "ideas", "number": 38, "text": "one line, no break"}

    stub = Stub()
    nova_site.NovaSiteHandler._post_board_comment(stub, dict(payload))
    if not stub.sent or stub.sent[0][0] != 400:
        return (f"a board comment with no author was not refused (got {stub.sent!r}) -- "
                "Cycle 479's two notes landed on the owner's board signed with his name")

    # Two-sided: a named author has to get past that check, or the refusal
    # above says nothing about the author field at all.
    original = nova_site.comment_on_row
    reached = []
    try:
        nova_site.comment_on_row = lambda *a, **k: (reached.append(a) or (False, "stubbed"))
        stub2 = Stub()
        try:
            nova_site.NovaSiteHandler._post_board_comment(stub2, dict(payload, author="Nova"))
        except Exception:
            # Whatever the route does *after* the writer is not this check's
            # business -- `reached` is appended inside the writer itself, so it
            # already records that the author check let this call through.
            pass
    finally:
        nova_site.comment_on_row = original
    if not reached:
        return ("a board comment naming 'Nova' as its author never reached the writer, so the "
                "refusal above is refusing something other than a missing author")
    return None


def _check_prompt_sweeps_every_namespace() -> Optional[str]:
    body = read_vault("projects/sokrates/projects/agora/nova/resources/prompt.md")
    if "kubectl get pods -A" not in body:
        return ("step 1's pod sweep no longer says `kubectl get pods -A` -- it read `-n agents` "
                "until Cycle 449, and a pod in `infra` crash-looped for 37 hours unseen")
    return None


def _check_prompt_does_not_hardcode_the_shared_checkout() -> Optional[str]:
    body = read_vault("projects/sokrates/projects/agora/nova/resources/prompt.md")
    bad = [line.strip() for line in body.splitlines()
           if "cd /data/workspace/" in line or line.strip().startswith("cd /data/workspace ")]
    if bad:
        return ("a command in prompt.md `cd`s straight into the shared checkout instead of "
                f"${{NOVA_WORKSPACE:-/data/workspace}}: {bad[0][:120]!r} -- concurrent cycles "
                "share that directory and would write over each other")
    return None


CORPUS = [
    Regression(
        slug="unattended-metered-provider",
        cycle="78",
        date="2026-08-10",
        surface="drove the code",
        failure=("A scheduled turn could run on the raw `anthropic:` API and spend the owner's "
                 "prepaid balance forever with nobody watching. His hard rule against it lived "
                 "only in a markdown file until this guard was written."),
        check=_check_unattended_metered,
    ),
    Regression(
        slug="board-comment-with-no-author",
        cycle="479",
        date="2026-08-26",
        surface="drove the code",
        failure=("The board-comment endpoint defaulted the author to the owner, so two notes I "
                 "posted from a shell landed on his live board signed with his name -- and then "
                 "set the unanswered-comment flag that outranks a 🔴, on a question he never asked."),
        check=_check_board_comment_names_its_author,
    ),
    Regression(
        slug="security-sweep-covered-only-the-checkouts",
        cycle="432",
        date="2026-08-25",
        surface="drove the code",
        failure=("The advisory sweep read only the repos this loop happens to clone, so it "
                 "printed 'nothing to act on' while sokrates-docs carried six open Dependabot "
                 "alerts, four of them high."),
        check=_check_security_sweep_covers_the_org,
    ),
    Regression(
        slug="an-ask-that-opens-with-a-statement",
        cycle="273",
        date="2026-08-20",
        surface="drove the code",
        failure=("A **Needs input** block spent 35 words on context before its first full stop, "
                 "so the owner had to mine a wall of text for the question. Six of the eight "
                 "asks written up to that morning opened with a statement."),
        check=_check_ask_opens_with_a_question,
    ),
    Regression(
        slug="pod-sweep-narrowed-to-one-namespace",
        cycle="449",
        date="2026-08-25",
        surface="read the text",
        failure=("The opening pod check said `-n agents`, so `whatsapp-bridge` crash-looped in "
                 "`infra` for 37 hours with 314 restarts while every cycle read a clean list."),
        check=_check_prompt_sweeps_every_namespace,
    ),
    Regression(
        slug="hardcoded-shared-checkout",
        cycle="≈460",
        date="2026-08-25",
        surface="read the text",
        failure=("Commands hardcoded `/data/workspace`, which is the shared checkout. Once "
                 "cycles began overlapping, two of them writing there at once would clobber "
                 "each other's working tree."),
        check=_check_prompt_does_not_hardcode_the_shared_checkout,
    ),
]


def run(corpus=None):
    """`(rows, status)` -- every entry checked, and the exit code to use."""
    rows, status = [], 0
    for item in corpus if corpus is not None else CORPUS:
        try:
            finding = item.check()
        except Unreadable as e:
            rows.append((item, "UNREADABLE", str(e)))
            status = max(status, 1)
            continue
        except Exception as e:  # a check that crashes has not said the failure is fixed
            rows.append((item, "UNREADABLE", f"the check itself raised {type(e).__name__}: {e}"))
            status = max(status, 1)
            continue
        if finding:
            rows.append((item, "REGRESSED", finding))
            status = 2
        else:
            rows.append((item, "held", ""))
    return rows, status


def format_report(rows, status):
    lines = []
    for item, verdict, detail in rows:
        if verdict == "held":
            lines.append(f"held        {item.slug}  (cycle {item.cycle}, {item.date}; {item.surface})")
        else:
            lines.append(f"{verdict}  {item.slug}  (cycle {item.cycle}, {item.date}; {item.surface})")
            lines.append(f"      what went wrong then: {item.failure}")
            lines.append(f"      what I see now: {detail}")
    lines.append(f"Checked {len(rows)} past failure(s) from this loop's own journal.")
    if status == 2:
        lines.append("A failure this loop already paid for once is back. Do not merge over this.")
    elif status == 1:
        lines.append("At least one check could not read what it needs, so this is not a clean run.")
    else:
        lines.append("Every past failure in the corpus is still fixed.")
    return "\n".join(lines)


def main(argv=None):
    rows, status = run()
    print(format_report(rows, status))
    return status


if __name__ == "__main__":
    raise SystemExit(main())
